export const testResponse = {
	name: "ARCANUM COLLECTIVE: SUBMERGED",
	date: "2025-10-10",
	location: "Hangaren, Copenhagen, Denmark",
	ticketPrice: "unknown",
	url: "https://www.hangaren.dk/events/2025/10/10-arcanum",
	artists: [
		{
			id: "artist-1",
			name: "Kliment",
			genres: [],
			popularity: 0,
			followers: "",
			image: "🎵",
			spotifyUrl: "",
			tracks: [],
		},
		{
			id: "artist-2",
			name: "Zzbing",
			genres: [],
			popularity: 0,
			followers: "",
			image: "🎵",
			spotifyUrl: "",
			tracks: [],
		},
		{
			id: "artist-3",
			name: "Oxyflux",
			genres: [],
			popularity: 0,
			followers: "",
			image: "🎵",
			spotifyUrl: "",
			tracks: [],
		},
		{
			id: "artist-4",
			name: "Krypto",
			genres: [],
			popularity: 0,
			followers: "",
			image: "🎵",
			spotifyUrl: "",
			tracks: [],
		},
		{
			id: "artist-5",
			name: "Florescence",
			genres: [],
			popularity: 0,
			followers: "",
			image: "🎵",
			spotifyUrl: "",
			tracks: [],
		},
		{
			id: "artist-6",
			name: "Freya Rose",
			genres: [],
			popularity: 0,
			followers: "",
			image: "🎵",
			spotifyUrl: "",
			tracks: [],
		},
		{
			id: "artist-7",
			name: "Lulla-Li",
			genres: [],
			popularity: 0,
			followers: "",
			image: "🎵",
			spotifyUrl: "",
			tracks: [],
		},
		{
			id: "artist-8",
			name: "Merlyn Silva",
			genres: [],
			popularity: 0,
			followers: "",
			image: "🎵",
			spotifyUrl: "",
			tracks: [],
		},
		{
			id: "artist-9",
			name: "Matt Nørgaard",
			genres: [],
			popularity: 0,
			followers: "",
			image: "🎵",
			spotifyUrl: "",
			tracks: [],
		},
	],
}
