export const testResponse = {
	name: "ARCANUM COLLECTIVE: SUBMERGED",
	date: "2025-10-10",
	location: "Hangaren, Copenhagen, Denmark",
	ticketPrice: "unknown",
	url: "https://www.hangaren.dk/events/2025/10/10-arcanum",
	artists: ["Kliment",
		"Zzbing",
		"Oxyflux",
		"Krypto",
		"Florescence",
		"Freya Rose",
		"Lulla-Li",
		"Merlyn Silva",
		"Matt Nørgaard"],
	genres: ["Dark Progressive Trance",
		"Psytrance",
		"Progressive Trance",
		"Psychedelic Trance",
		"Electronic",
		"Techno",
		"Trance"],
}
